esphome:
  name: timed-replay-controller
  friendly_name: timed-replay-controller

substitutions:
  # Modify variables based on your settings
  devicename: timed-replay-controller

esp8266:
  board: esp01_1m

# Enable logging
logger:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

captive_portal:


# MQTT Configuration
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  port: !secret mqtt_port
  discovery: true
  discovery_retain: true
  birth_message:
    topic: ${devicename}/status
    payload: online
    retain: true
  will_message:
    topic: ${devicename}/status
    payload: offline
    retain: true

# Number inputs for configurable timing
number:
  - platform: template
    name: "HT Pump Run Duration"
    id: run_duration
    optimistic: true
    min_value: 1
    max_value: 60
    step: 1
    initial_value: 15
    unit_of_measurement: "min"
    mode: slider
    restore_value: true
    on_value:
      - logger.log:
          format: "Run duration changed to %.0f minutes"
          args: ['x']
      - if:
          condition:
            switch.is_on: auto_mode
          then:
            - script.execute: auto_cycle_script

  - platform: template
    name: "HT Pump Cycle Interval"
    id: cycle_interval
    optimistic: true
    min_value: 5
    max_value: 180
    step: 5
    initial_value: 45
    unit_of_measurement: "min"
    mode: slider
    restore_value: true
    on_value:
      - logger.log:
          format: "Cycle interval changed to %.0f minutes"
          args: ['x']
      - if:
          condition:
            switch.is_on: auto_mode
          then:
            - script.execute: auto_cycle_script

switch:
  - platform: gpio
    pin: GPIO0
    name: "Switch"
    id: switch
    inverted: true

  # Enable/Disable automatic cycling
  - platform: template
    name: "Auto Mode"
    id: auto_mode
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - logger.log: "Auto mode enabled"
      - script.execute: auto_cycle_script
    turn_off_action:
      - logger.log: "Auto mode disabled"
      - script.stop: auto_cycle_script

  # The following can be omitted
  - platform: restart
    name: ${devicename} restart

sensor:
  - platform: wifi_signal
    name: ${devicename} wifi signal
    update_interval: 60s

  # human readable uptime sensor output to the text sensor above
  - platform: uptime
    name: ${devicename} Uptime in Days
    id: uptime_sensor_days
    update_interval: 600s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor_days).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

time:
  - platform: sntp
    id: homeassistant_time
    timezone: "Asia/Kolkata"  # Change to your timezone
    servers:
      - !secret ntp_server_1  # Your Primary server with Chrony
      - !secret ntp_server_2  # Your Secondary server with Chrony
    update_interval: 10min

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: $devicename Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: $devicename IP
      address_0:
        name: $devicename IPv4
      address_1:
        name: $devicename IPv6 Local Link
      address_2:
        name: $devicename IPV6 1
      address_3:
        name: $devicename IPV6 2
    bssid:
      name: $devicename BSSID

  # human readable update text sensor from sensor:uptime
  - platform: template
    name: Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start

one_wire:
  - platform: gpio
    pin: GPIO2

# Script for automatic cycling
script:
  - id: auto_cycle_script
    mode: restart
    then:
      - while:
          condition:
            switch.is_on: auto_mode
          then:
            # Turn on the pump
            - switch.turn_on: switch
            - logger.log: "Pump turned ON (auto cycle)"
            
            # Wait for run duration
            - delay: !lambda "return id(run_duration).state * 60 * 1000;"
            
            # Turn off the pump
            - switch.turn_off: switch
            - logger.log: "Pump turned OFF (auto cycle)"
            
            # Calculate wait time (interval - run duration)
            - delay: !lambda "return (id(cycle_interval).state - id(run_duration).state) * 60 * 1000;"

# Start auto mode on boot
interval:
  - interval: 300s
    then:
      - if:
          condition:
            and:
              - switch.is_on: auto_mode
              - script.is_running: auto_cycle_script
          then:
            - logger.log: "Auto cycle script is running"
          else:
            - if:
                condition:
                  switch.is_on: auto_mode
                then:
                  - script.execute: auto_cycle_script
